name: paraiso_canino
description: "Pagina Web desarrollada para la veterinaria Paraíso Canino."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  flutter_secure_storage: ^9.2.2
  cupertino_icons: ^1.0.8
  easy_sidemenu: ^0.6.0
  path_provider: ^2.0.11
  flutter_svg: ^2.0.10+1
  flutter_bloc: ^8.1.6
  google_fonts: ^6.2.1
  google_maps: ^6.3.0
  equatable: ^2.0.5
  lottie: ^3.1.2
  dio: ^5.6.0
  intl: ^0.19.0
  pdf: ^3.11.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
